apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels: 
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.container.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "backend.fullname" . }}
          image: {{ .Values.backend.container.image }}
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: {{ .Values.backend.container.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_HOST
      imagePullSecrets:
      - name: regcred

